/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LocaleGlobalLayoutRouteImport } from './routes/$locale/_globalLayout'
import { Route as LocaleGlobalLayoutIndexRouteImport } from './routes/$locale/_globalLayout/index'
import { Route as LocaleGlobalLayoutUserGuideRouteImport } from './routes/$locale/_globalLayout/user-guide'
import { Route as LocaleGlobalLayoutTermsAndConditionsRouteImport } from './routes/$locale/_globalLayout/terms-and-conditions'
import { Route as LocaleGlobalLayoutSignupRouteImport } from './routes/$locale/_globalLayout/signup'
import { Route as LocaleGlobalLayoutShareProgressRouteImport } from './routes/$locale/_globalLayout/share-progress'
import { Route as LocaleGlobalLayoutPrivacyPolicyRouteImport } from './routes/$locale/_globalLayout/privacy-policy'
import { Route as LocaleGlobalLayoutOurVisionRouteImport } from './routes/$locale/_globalLayout/our-vision'
import { Route as LocaleGlobalLayoutLoginRouteImport } from './routes/$locale/_globalLayout/login'
import { Route as LocaleGlobalLayoutForgetPasswordRouteImport } from './routes/$locale/_globalLayout/forget-password'
import { Route as LocaleGlobalLayoutContactRouteImport } from './routes/$locale/_globalLayout/contact'
import { Route as LocaleGlobalLayoutAuthRouteImport } from './routes/$locale/_globalLayout/_auth'
import { Route as LocaleGlobalLayoutAuthVerifyEmailRouteImport } from './routes/$locale/_globalLayout/_auth/verify-email'
import { Route as LocaleGlobalLayoutAuthAppRouteRouteImport } from './routes/$locale/_globalLayout/_auth/app.route'
import { Route as LocaleGlobalLayoutAuthAppIndexRouteImport } from './routes/$locale/_globalLayout/_auth/app.index'
import { Route as LocaleGlobalLayoutAuthAppAccountRouteImport } from './routes/$locale/_globalLayout/_auth/app.account'
import { Route as LocaleGlobalLayoutAuthAppLevelsIndexRouteImport } from './routes/$locale/_globalLayout/_auth/app.levels.index'
import { Route as LocaleGlobalLayoutAuthAppAdminAiSettingsRouteImport } from './routes/$locale/_globalLayout/_auth/app.admin.ai-settings'
import { Route as LocaleGlobalLayoutAuthAppLevelsIdIndexRouteImport } from './routes/$locale/_globalLayout/_auth/app.levels.$id.index'
import { Route as LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteImport } from './routes/$locale/_globalLayout/_auth/app.levels.$id.$day.$lessonName.route'
import { Route as LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRouteImport } from './routes/$locale/_globalLayout/_auth/app.levels.$id.$day.$lessonName.index'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleGlobalLayoutRoute = LocaleGlobalLayoutRouteImport.update({
  id: '/$locale/_globalLayout',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleGlobalLayoutIndexRoute = LocaleGlobalLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleGlobalLayoutRoute,
} as any)
const LocaleGlobalLayoutUserGuideRoute =
  LocaleGlobalLayoutUserGuideRouteImport.update({
    id: '/user-guide',
    path: '/user-guide',
    getParentRoute: () => LocaleGlobalLayoutRoute,
  } as any)
const LocaleGlobalLayoutTermsAndConditionsRoute =
  LocaleGlobalLayoutTermsAndConditionsRouteImport.update({
    id: '/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => LocaleGlobalLayoutRoute,
  } as any)
const LocaleGlobalLayoutSignupRoute =
  LocaleGlobalLayoutSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => LocaleGlobalLayoutRoute,
  } as any)
const LocaleGlobalLayoutShareProgressRoute =
  LocaleGlobalLayoutShareProgressRouteImport.update({
    id: '/share-progress',
    path: '/share-progress',
    getParentRoute: () => LocaleGlobalLayoutRoute,
  } as any)
const LocaleGlobalLayoutPrivacyPolicyRoute =
  LocaleGlobalLayoutPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => LocaleGlobalLayoutRoute,
  } as any)
const LocaleGlobalLayoutOurVisionRoute =
  LocaleGlobalLayoutOurVisionRouteImport.update({
    id: '/our-vision',
    path: '/our-vision',
    getParentRoute: () => LocaleGlobalLayoutRoute,
  } as any)
const LocaleGlobalLayoutLoginRoute = LocaleGlobalLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleGlobalLayoutRoute,
} as any)
const LocaleGlobalLayoutForgetPasswordRoute =
  LocaleGlobalLayoutForgetPasswordRouteImport.update({
    id: '/forget-password',
    path: '/forget-password',
    getParentRoute: () => LocaleGlobalLayoutRoute,
  } as any)
const LocaleGlobalLayoutContactRoute =
  LocaleGlobalLayoutContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => LocaleGlobalLayoutRoute,
  } as any)
const LocaleGlobalLayoutAuthRoute = LocaleGlobalLayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LocaleGlobalLayoutRoute,
} as any)
const LocaleGlobalLayoutAuthVerifyEmailRoute =
  LocaleGlobalLayoutAuthVerifyEmailRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => LocaleGlobalLayoutAuthRoute,
  } as any)
const LocaleGlobalLayoutAuthAppRouteRoute =
  LocaleGlobalLayoutAuthAppRouteRouteImport.update({
    id: '/app',
    path: '/app',
    getParentRoute: () => LocaleGlobalLayoutAuthRoute,
  } as any)
const LocaleGlobalLayoutAuthAppIndexRoute =
  LocaleGlobalLayoutAuthAppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleGlobalLayoutAuthAppRouteRoute,
  } as any)
const LocaleGlobalLayoutAuthAppAccountRoute =
  LocaleGlobalLayoutAuthAppAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LocaleGlobalLayoutAuthAppRouteRoute,
  } as any)
const LocaleGlobalLayoutAuthAppLevelsIndexRoute =
  LocaleGlobalLayoutAuthAppLevelsIndexRouteImport.update({
    id: '/levels/',
    path: '/levels/',
    getParentRoute: () => LocaleGlobalLayoutAuthAppRouteRoute,
  } as any)
const LocaleGlobalLayoutAuthAppAdminAiSettingsRoute =
  LocaleGlobalLayoutAuthAppAdminAiSettingsRouteImport.update({
    id: '/admin/ai-settings',
    path: '/admin/ai-settings',
    getParentRoute: () => LocaleGlobalLayoutAuthAppRouteRoute,
  } as any)
const LocaleGlobalLayoutAuthAppLevelsIdIndexRoute =
  LocaleGlobalLayoutAuthAppLevelsIdIndexRouteImport.update({
    id: '/levels/$id/',
    path: '/levels/$id/',
    getParentRoute: () => LocaleGlobalLayoutAuthAppRouteRoute,
  } as any)
const LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRoute =
  LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteImport.update({
    id: '/levels/$id/$day/$lessonName',
    path: '/levels/$id/$day/$lessonName',
    getParentRoute: () => LocaleGlobalLayoutAuthAppRouteRoute,
  } as any)
const LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRoute =
  LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/$locale': typeof LocaleGlobalLayoutAuthRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale/contact': typeof LocaleGlobalLayoutContactRoute
  '/$locale/forget-password': typeof LocaleGlobalLayoutForgetPasswordRoute
  '/$locale/login': typeof LocaleGlobalLayoutLoginRoute
  '/$locale/our-vision': typeof LocaleGlobalLayoutOurVisionRoute
  '/$locale/privacy-policy': typeof LocaleGlobalLayoutPrivacyPolicyRoute
  '/$locale/share-progress': typeof LocaleGlobalLayoutShareProgressRoute
  '/$locale/signup': typeof LocaleGlobalLayoutSignupRoute
  '/$locale/terms-and-conditions': typeof LocaleGlobalLayoutTermsAndConditionsRoute
  '/$locale/user-guide': typeof LocaleGlobalLayoutUserGuideRoute
  '/$locale/': typeof LocaleGlobalLayoutIndexRoute
  '/$locale/app': typeof LocaleGlobalLayoutAuthAppRouteRouteWithChildren
  '/$locale/verify-email': typeof LocaleGlobalLayoutAuthVerifyEmailRoute
  '/$locale/app/account': typeof LocaleGlobalLayoutAuthAppAccountRoute
  '/$locale/app/': typeof LocaleGlobalLayoutAuthAppIndexRoute
  '/$locale/app/admin/ai-settings': typeof LocaleGlobalLayoutAuthAppAdminAiSettingsRoute
  '/$locale/app/levels/': typeof LocaleGlobalLayoutAuthAppLevelsIndexRoute
  '/$locale/app/levels/$id/': typeof LocaleGlobalLayoutAuthAppLevelsIdIndexRoute
  '/$locale/app/levels/$id/$day/$lessonName': typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteWithChildren
  '/$locale/app/levels/$id/$day/$lessonName/': typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale': typeof LocaleGlobalLayoutIndexRoute
  '/$locale/contact': typeof LocaleGlobalLayoutContactRoute
  '/$locale/forget-password': typeof LocaleGlobalLayoutForgetPasswordRoute
  '/$locale/login': typeof LocaleGlobalLayoutLoginRoute
  '/$locale/our-vision': typeof LocaleGlobalLayoutOurVisionRoute
  '/$locale/privacy-policy': typeof LocaleGlobalLayoutPrivacyPolicyRoute
  '/$locale/share-progress': typeof LocaleGlobalLayoutShareProgressRoute
  '/$locale/signup': typeof LocaleGlobalLayoutSignupRoute
  '/$locale/terms-and-conditions': typeof LocaleGlobalLayoutTermsAndConditionsRoute
  '/$locale/user-guide': typeof LocaleGlobalLayoutUserGuideRoute
  '/$locale/verify-email': typeof LocaleGlobalLayoutAuthVerifyEmailRoute
  '/$locale/app/account': typeof LocaleGlobalLayoutAuthAppAccountRoute
  '/$locale/app': typeof LocaleGlobalLayoutAuthAppIndexRoute
  '/$locale/app/admin/ai-settings': typeof LocaleGlobalLayoutAuthAppAdminAiSettingsRoute
  '/$locale/app/levels': typeof LocaleGlobalLayoutAuthAppLevelsIndexRoute
  '/$locale/app/levels/$id': typeof LocaleGlobalLayoutAuthAppLevelsIdIndexRoute
  '/$locale/app/levels/$id/$day/$lessonName': typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/$locale/_globalLayout': typeof LocaleGlobalLayoutRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/$locale/_globalLayout/_auth': typeof LocaleGlobalLayoutAuthRouteWithChildren
  '/$locale/_globalLayout/contact': typeof LocaleGlobalLayoutContactRoute
  '/$locale/_globalLayout/forget-password': typeof LocaleGlobalLayoutForgetPasswordRoute
  '/$locale/_globalLayout/login': typeof LocaleGlobalLayoutLoginRoute
  '/$locale/_globalLayout/our-vision': typeof LocaleGlobalLayoutOurVisionRoute
  '/$locale/_globalLayout/privacy-policy': typeof LocaleGlobalLayoutPrivacyPolicyRoute
  '/$locale/_globalLayout/share-progress': typeof LocaleGlobalLayoutShareProgressRoute
  '/$locale/_globalLayout/signup': typeof LocaleGlobalLayoutSignupRoute
  '/$locale/_globalLayout/terms-and-conditions': typeof LocaleGlobalLayoutTermsAndConditionsRoute
  '/$locale/_globalLayout/user-guide': typeof LocaleGlobalLayoutUserGuideRoute
  '/$locale/_globalLayout/': typeof LocaleGlobalLayoutIndexRoute
  '/$locale/_globalLayout/_auth/app': typeof LocaleGlobalLayoutAuthAppRouteRouteWithChildren
  '/$locale/_globalLayout/_auth/verify-email': typeof LocaleGlobalLayoutAuthVerifyEmailRoute
  '/$locale/_globalLayout/_auth/app/account': typeof LocaleGlobalLayoutAuthAppAccountRoute
  '/$locale/_globalLayout/_auth/app/': typeof LocaleGlobalLayoutAuthAppIndexRoute
  '/$locale/_globalLayout/_auth/app/admin/ai-settings': typeof LocaleGlobalLayoutAuthAppAdminAiSettingsRoute
  '/$locale/_globalLayout/_auth/app/levels/': typeof LocaleGlobalLayoutAuthAppLevelsIndexRoute
  '/$locale/_globalLayout/_auth/app/levels/$id/': typeof LocaleGlobalLayoutAuthAppLevelsIdIndexRoute
  '/$locale/_globalLayout/_auth/app/levels/$id/$day/$lessonName': typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteWithChildren
  '/$locale/_globalLayout/_auth/app/levels/$id/$day/$lessonName/': typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/$locale'
    | '/auth/callback'
    | '/$locale/contact'
    | '/$locale/forget-password'
    | '/$locale/login'
    | '/$locale/our-vision'
    | '/$locale/privacy-policy'
    | '/$locale/share-progress'
    | '/$locale/signup'
    | '/$locale/terms-and-conditions'
    | '/$locale/user-guide'
    | '/$locale/'
    | '/$locale/app'
    | '/$locale/verify-email'
    | '/$locale/app/account'
    | '/$locale/app/'
    | '/$locale/app/admin/ai-settings'
    | '/$locale/app/levels/'
    | '/$locale/app/levels/$id/'
    | '/$locale/app/levels/$id/$day/$lessonName'
    | '/$locale/app/levels/$id/$day/$lessonName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/auth/callback'
    | '/$locale'
    | '/$locale/contact'
    | '/$locale/forget-password'
    | '/$locale/login'
    | '/$locale/our-vision'
    | '/$locale/privacy-policy'
    | '/$locale/share-progress'
    | '/$locale/signup'
    | '/$locale/terms-and-conditions'
    | '/$locale/user-guide'
    | '/$locale/verify-email'
    | '/$locale/app/account'
    | '/$locale/app'
    | '/$locale/app/admin/ai-settings'
    | '/$locale/app/levels'
    | '/$locale/app/levels/$id'
    | '/$locale/app/levels/$id/$day/$lessonName'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/$locale/_globalLayout'
    | '/auth/callback'
    | '/$locale/_globalLayout/_auth'
    | '/$locale/_globalLayout/contact'
    | '/$locale/_globalLayout/forget-password'
    | '/$locale/_globalLayout/login'
    | '/$locale/_globalLayout/our-vision'
    | '/$locale/_globalLayout/privacy-policy'
    | '/$locale/_globalLayout/share-progress'
    | '/$locale/_globalLayout/signup'
    | '/$locale/_globalLayout/terms-and-conditions'
    | '/$locale/_globalLayout/user-guide'
    | '/$locale/_globalLayout/'
    | '/$locale/_globalLayout/_auth/app'
    | '/$locale/_globalLayout/_auth/verify-email'
    | '/$locale/_globalLayout/_auth/app/account'
    | '/$locale/_globalLayout/_auth/app/'
    | '/$locale/_globalLayout/_auth/app/admin/ai-settings'
    | '/$locale/_globalLayout/_auth/app/levels/'
    | '/$locale/_globalLayout/_auth/app/levels/$id/'
    | '/$locale/_globalLayout/_auth/app/levels/$id/$day/$lessonName'
    | '/$locale/_globalLayout/_auth/app/levels/$id/$day/$lessonName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  LocaleGlobalLayoutRoute: typeof LocaleGlobalLayoutRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_globalLayout': {
      id: '/$locale/_globalLayout'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleGlobalLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_globalLayout/': {
      id: '/$locale/_globalLayout/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleGlobalLayoutIndexRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/user-guide': {
      id: '/$locale/_globalLayout/user-guide'
      path: '/user-guide'
      fullPath: '/$locale/user-guide'
      preLoaderRoute: typeof LocaleGlobalLayoutUserGuideRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/terms-and-conditions': {
      id: '/$locale/_globalLayout/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/$locale/terms-and-conditions'
      preLoaderRoute: typeof LocaleGlobalLayoutTermsAndConditionsRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/signup': {
      id: '/$locale/_globalLayout/signup'
      path: '/signup'
      fullPath: '/$locale/signup'
      preLoaderRoute: typeof LocaleGlobalLayoutSignupRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/share-progress': {
      id: '/$locale/_globalLayout/share-progress'
      path: '/share-progress'
      fullPath: '/$locale/share-progress'
      preLoaderRoute: typeof LocaleGlobalLayoutShareProgressRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/privacy-policy': {
      id: '/$locale/_globalLayout/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$locale/privacy-policy'
      preLoaderRoute: typeof LocaleGlobalLayoutPrivacyPolicyRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/our-vision': {
      id: '/$locale/_globalLayout/our-vision'
      path: '/our-vision'
      fullPath: '/$locale/our-vision'
      preLoaderRoute: typeof LocaleGlobalLayoutOurVisionRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/login': {
      id: '/$locale/_globalLayout/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleGlobalLayoutLoginRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/forget-password': {
      id: '/$locale/_globalLayout/forget-password'
      path: '/forget-password'
      fullPath: '/$locale/forget-password'
      preLoaderRoute: typeof LocaleGlobalLayoutForgetPasswordRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/contact': {
      id: '/$locale/_globalLayout/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleGlobalLayoutContactRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/_auth': {
      id: '/$locale/_globalLayout/_auth'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthRouteImport
      parentRoute: typeof LocaleGlobalLayoutRoute
    }
    '/$locale/_globalLayout/_auth/verify-email': {
      id: '/$locale/_globalLayout/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/$locale/verify-email'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthVerifyEmailRouteImport
      parentRoute: typeof LocaleGlobalLayoutAuthRoute
    }
    '/$locale/_globalLayout/_auth/app': {
      id: '/$locale/_globalLayout/_auth/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthAppRouteRouteImport
      parentRoute: typeof LocaleGlobalLayoutAuthRoute
    }
    '/$locale/_globalLayout/_auth/app/': {
      id: '/$locale/_globalLayout/_auth/app/'
      path: '/'
      fullPath: '/$locale/app/'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthAppIndexRouteImport
      parentRoute: typeof LocaleGlobalLayoutAuthAppRouteRoute
    }
    '/$locale/_globalLayout/_auth/app/account': {
      id: '/$locale/_globalLayout/_auth/app/account'
      path: '/account'
      fullPath: '/$locale/app/account'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthAppAccountRouteImport
      parentRoute: typeof LocaleGlobalLayoutAuthAppRouteRoute
    }
    '/$locale/_globalLayout/_auth/app/levels/': {
      id: '/$locale/_globalLayout/_auth/app/levels/'
      path: '/levels'
      fullPath: '/$locale/app/levels/'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthAppLevelsIndexRouteImport
      parentRoute: typeof LocaleGlobalLayoutAuthAppRouteRoute
    }
    '/$locale/_globalLayout/_auth/app/admin/ai-settings': {
      id: '/$locale/_globalLayout/_auth/app/admin/ai-settings'
      path: '/admin/ai-settings'
      fullPath: '/$locale/app/admin/ai-settings'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthAppAdminAiSettingsRouteImport
      parentRoute: typeof LocaleGlobalLayoutAuthAppRouteRoute
    }
    '/$locale/_globalLayout/_auth/app/levels/$id/': {
      id: '/$locale/_globalLayout/_auth/app/levels/$id/'
      path: '/levels/$id'
      fullPath: '/$locale/app/levels/$id/'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthAppLevelsIdIndexRouteImport
      parentRoute: typeof LocaleGlobalLayoutAuthAppRouteRoute
    }
    '/$locale/_globalLayout/_auth/app/levels/$id/$day/$lessonName': {
      id: '/$locale/_globalLayout/_auth/app/levels/$id/$day/$lessonName'
      path: '/levels/$id/$day/$lessonName'
      fullPath: '/$locale/app/levels/$id/$day/$lessonName'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteImport
      parentRoute: typeof LocaleGlobalLayoutAuthAppRouteRoute
    }
    '/$locale/_globalLayout/_auth/app/levels/$id/$day/$lessonName/': {
      id: '/$locale/_globalLayout/_auth/app/levels/$id/$day/$lessonName/'
      path: '/'
      fullPath: '/$locale/app/levels/$id/$day/$lessonName/'
      preLoaderRoute: typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRouteImport
      parentRoute: typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRoute
    }
  }
}

interface LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteChildren {
  LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRoute: typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRoute
}

const LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteChildren: LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteChildren =
  {
    LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRoute:
      LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameIndexRoute,
  }

const LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteWithChildren =
  LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRoute._addFileChildren(
    LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteChildren,
  )

interface LocaleGlobalLayoutAuthAppRouteRouteChildren {
  LocaleGlobalLayoutAuthAppAccountRoute: typeof LocaleGlobalLayoutAuthAppAccountRoute
  LocaleGlobalLayoutAuthAppIndexRoute: typeof LocaleGlobalLayoutAuthAppIndexRoute
  LocaleGlobalLayoutAuthAppAdminAiSettingsRoute: typeof LocaleGlobalLayoutAuthAppAdminAiSettingsRoute
  LocaleGlobalLayoutAuthAppLevelsIndexRoute: typeof LocaleGlobalLayoutAuthAppLevelsIndexRoute
  LocaleGlobalLayoutAuthAppLevelsIdIndexRoute: typeof LocaleGlobalLayoutAuthAppLevelsIdIndexRoute
  LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRoute: typeof LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteWithChildren
}

const LocaleGlobalLayoutAuthAppRouteRouteChildren: LocaleGlobalLayoutAuthAppRouteRouteChildren =
  {
    LocaleGlobalLayoutAuthAppAccountRoute:
      LocaleGlobalLayoutAuthAppAccountRoute,
    LocaleGlobalLayoutAuthAppIndexRoute: LocaleGlobalLayoutAuthAppIndexRoute,
    LocaleGlobalLayoutAuthAppAdminAiSettingsRoute:
      LocaleGlobalLayoutAuthAppAdminAiSettingsRoute,
    LocaleGlobalLayoutAuthAppLevelsIndexRoute:
      LocaleGlobalLayoutAuthAppLevelsIndexRoute,
    LocaleGlobalLayoutAuthAppLevelsIdIndexRoute:
      LocaleGlobalLayoutAuthAppLevelsIdIndexRoute,
    LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRoute:
      LocaleGlobalLayoutAuthAppLevelsIdDayLessonNameRouteRouteWithChildren,
  }

const LocaleGlobalLayoutAuthAppRouteRouteWithChildren =
  LocaleGlobalLayoutAuthAppRouteRoute._addFileChildren(
    LocaleGlobalLayoutAuthAppRouteRouteChildren,
  )

interface LocaleGlobalLayoutAuthRouteChildren {
  LocaleGlobalLayoutAuthAppRouteRoute: typeof LocaleGlobalLayoutAuthAppRouteRouteWithChildren
  LocaleGlobalLayoutAuthVerifyEmailRoute: typeof LocaleGlobalLayoutAuthVerifyEmailRoute
}

const LocaleGlobalLayoutAuthRouteChildren: LocaleGlobalLayoutAuthRouteChildren =
  {
    LocaleGlobalLayoutAuthAppRouteRoute:
      LocaleGlobalLayoutAuthAppRouteRouteWithChildren,
    LocaleGlobalLayoutAuthVerifyEmailRoute:
      LocaleGlobalLayoutAuthVerifyEmailRoute,
  }

const LocaleGlobalLayoutAuthRouteWithChildren =
  LocaleGlobalLayoutAuthRoute._addFileChildren(
    LocaleGlobalLayoutAuthRouteChildren,
  )

interface LocaleGlobalLayoutRouteChildren {
  LocaleGlobalLayoutAuthRoute: typeof LocaleGlobalLayoutAuthRouteWithChildren
  LocaleGlobalLayoutContactRoute: typeof LocaleGlobalLayoutContactRoute
  LocaleGlobalLayoutForgetPasswordRoute: typeof LocaleGlobalLayoutForgetPasswordRoute
  LocaleGlobalLayoutLoginRoute: typeof LocaleGlobalLayoutLoginRoute
  LocaleGlobalLayoutOurVisionRoute: typeof LocaleGlobalLayoutOurVisionRoute
  LocaleGlobalLayoutPrivacyPolicyRoute: typeof LocaleGlobalLayoutPrivacyPolicyRoute
  LocaleGlobalLayoutShareProgressRoute: typeof LocaleGlobalLayoutShareProgressRoute
  LocaleGlobalLayoutSignupRoute: typeof LocaleGlobalLayoutSignupRoute
  LocaleGlobalLayoutTermsAndConditionsRoute: typeof LocaleGlobalLayoutTermsAndConditionsRoute
  LocaleGlobalLayoutUserGuideRoute: typeof LocaleGlobalLayoutUserGuideRoute
  LocaleGlobalLayoutIndexRoute: typeof LocaleGlobalLayoutIndexRoute
}

const LocaleGlobalLayoutRouteChildren: LocaleGlobalLayoutRouteChildren = {
  LocaleGlobalLayoutAuthRoute: LocaleGlobalLayoutAuthRouteWithChildren,
  LocaleGlobalLayoutContactRoute: LocaleGlobalLayoutContactRoute,
  LocaleGlobalLayoutForgetPasswordRoute: LocaleGlobalLayoutForgetPasswordRoute,
  LocaleGlobalLayoutLoginRoute: LocaleGlobalLayoutLoginRoute,
  LocaleGlobalLayoutOurVisionRoute: LocaleGlobalLayoutOurVisionRoute,
  LocaleGlobalLayoutPrivacyPolicyRoute: LocaleGlobalLayoutPrivacyPolicyRoute,
  LocaleGlobalLayoutShareProgressRoute: LocaleGlobalLayoutShareProgressRoute,
  LocaleGlobalLayoutSignupRoute: LocaleGlobalLayoutSignupRoute,
  LocaleGlobalLayoutTermsAndConditionsRoute:
    LocaleGlobalLayoutTermsAndConditionsRoute,
  LocaleGlobalLayoutUserGuideRoute: LocaleGlobalLayoutUserGuideRoute,
  LocaleGlobalLayoutIndexRoute: LocaleGlobalLayoutIndexRoute,
}

const LocaleGlobalLayoutRouteWithChildren =
  LocaleGlobalLayoutRoute._addFileChildren(LocaleGlobalLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  LocaleGlobalLayoutRoute: LocaleGlobalLayoutRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
